export const environment = {
  production: false,
  apiUrl: 'https://api.example.com',
  claudeApiUrl: 'https://api.anthropic.com/v1',
  apiPatient:'http://localhost/rapport/patient.php',
  apiStaff:'http://localhost/rapport/staff.php',
  apiConsultation:'http://localhost/rapport/consultation.php',
  apiProduit:'http://localhost/rapport/produit.php',
  apiOrdonnance:'http://localhost/rapport/ordonnance.php',
  apiRV:'http://localhost/rapport/appointment.php',
  apiArticle:'http://localhost/rapport/article.php',
  apiDepartement:'http://localhost/rapport/departement.php',
  apiHoraire:'http://localhost/rapport/horaire.php',
  apiFacture:'http://localhost/rapport/facture.php',
  apiTest:'http://localhost/rapport/labtest.php',
  apiOperation:'http://localhost/rapport/operation.php',
  apisalle:'http://localhost/rapport/salle.php',
  apiEtage:'http://localhost/rapport/etage.php',
  apiUrgence:'http://localhost/rapport/urgence.php',
  apiResultatLab:'http://localhost/rapport/labResult.php',
  apiMouvement:'http://localhost/rapport/mouvement.php',
  apiCommande:'http://localhost/rapport/commande.php',
  apiDossier:'http://localhost/rapport/dossier.php'
};
